openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    CategorizationRule:
      type: object
      description: Block to describe that a rule has been applied.
      properties:
        id:
          type: string
          description: Rule ID that was applied to categorize transaction
        affectedFields:
          type: array
          description: "Block describing all the fields that were changed as result of the rule.\t"
          items:
            type: object
            properties:
              field:
                type: string
                description: "The transaction field what was changed as result of the rule\t"
