openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    ComprehensionMetaData:
      title: ComprehensionMetaData
      type: object
      properties:
        additionalInfo:
          type: array
          items:
            $ref: ./ComprehensionInfo.yaml#/components/schemas/ComprehensionInfo
