openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    DateTimeStamp:
      title: DateTimeStamp
      type: object
      description: Standard Date and time stamp across all domain and entities
      properties:
        dateTimeStamp:
          type: string
          description: 'Date in ISO 8601 UTC format - "yyyy-MM-dd''''T''''HH:mm:ss''''Z''''" with timezone'
          example: 'yyyy-MM-dd''''T''''HH:mm:ss Z'
      required:
        - dateTimeStamp
