openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        detail:
          type: string
        moreInfo:
          type: string
        category:
          type: string
        cause:
          type: object
          properties:
            code:
              type: string
            type:
              type: string
              enum:
                - client
                - service
                - provider
            source:
              type: string
            message:
              type: string
            httpStatusCode:
              type: string
