openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    ProcessorInfo:
      title: ProcessorInfo
      type: object
      description: Processor information for entity processing
      properties:
        processorExecutionOrderId:
          type: integer
        processorName:
          type: string
        processorStatus:
          type: string
          enum:
            - init
            - success
            - failed
        error:
          type: array
          items:
            $ref: ./Error.yaml#/components/schemas/Error
