openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Dispute:
      title: Dispute
      type: object
      description: 'Describes the disputed transaction. The type of the dispute and other particulars like amount, finalized dates.'
      properties:
        id:
          $ref: ../../common/v1/Id.yaml#/components/schemas/Id
        amount:
          $ref: ../../common/v1/Money.yaml#/components/schemas/Money
        reason:
          type: string
          enum:
            - fraudulent
            - duplicate
            - notasdescribed
            - cancelled
            - notreceived
            - other
            - buyerfavor
            - sellerfavor
          description: 'Reason for dispute like fraudulent, duplicate, cancelled etc'
        explanation:
          type: string
          description: The explanation given for Dispute
        finalizedDate:
          $ref: ../../common/v1/DateTimeStamp.yaml#/components/schemas/DateTimeStamp
        evidenceDueDate:
          $ref: ../../common/v1/DateTimeStamp.yaml#/components/schemas/DateTimeStamp
        createdDate:
          $ref: ../../common/v1/DateTimeStamp.yaml#/components/schemas/DateTimeStamp
