openapi: 3.1.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    PaymentTransactionEvent:
      title: PaymentTransactionEvent
      type: object
      description: PaymenTransactionEvent
      properties:
        data:
          $ref: ../../../entities/payment/v1/PaymentTransaction.yaml#/components/schemas/PaymentTransaction
        metaData:
          $ref: ../../../entities/common/v1/MetaData.yaml#/components/schemas/MetaData
