openapi: 3.1.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    TransferEvent:
      title: TransferEvent
      type: object
      description: TransferEvent
      properties:
        data:
          $ref: ../../../entities/payment/v1/Transfer.yaml#/components/schemas/Transfer
        metaData:
          $ref: ../../../entities/common/v1/MetaData.yaml#/components/schemas/MetaData
