openapi: 3.1.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    InvestmentTransaction:
      title: InvestmentTransaction
      type: object
      properties:
        id:
          type: string
    InvestmentAccount:
      title: InvestmentAccount
      type: object
      properties:
        id:
          type: string
