openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Discount:
      title: Discounts
      type: object
      properties:
        id:
          $ref: ../../common/v1/Id.yaml#/components/schemas/Id
        name:
          type: string
          description: Name of the discount
        amount:
          $ref: ../../common/v1/Money.yaml#/components/schemas/Money
      description: Discount Details
