openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    FulfillmentLineItem:
      title: FulfillmentLineItem
      type: object
      description: ''
      properties:
        variantId:
          $ref: ../../common/v1/Id.yaml#/components/schemas/Id
        orderId:
          type: array
          items:
            $ref: ../../common/v1/Link.yaml#/components/schemas/Link
        lineItem:
          $ref: ../../common/v1/LineItem.yaml#/components/schemas/LineItem
