openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    OrderLineItem:
      $ref: ../../common/v1/LineItem.yaml#/components/schemas/LineItem
