openapi: 3.0.0
info:
  title: idx3
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Order:
      title: Order
      type: object
      description: Order Object
      properties:
        id:
          $ref: ../../common/v1/Id.yaml#/components/schemas/Id
        status:
          type: string
          enum:
            - created
            - paid
            - cancelled
            - fulfilled
            - refunded
            - returned
          description: 'created, paid, cancelled, fulfilled, refunded, returned'
        date:
          $ref: ../../common/v1/DateTimeStamp.yaml#/components/schemas/DateTimeStamp
        dueDate:
          $ref: ../../common/v1/DateTimeStamp.yaml#/components/schemas/DateTimeStamp
        total:
          $ref: ../../common/v1/Money.yaml#/components/schemas/Money
        taxes:
          $ref: ../../common/v1/Money.yaml#/components/schemas/Money
        billingAddress:
          $ref: ../../common/v1/Address.yaml#/components/schemas/Address
        shippingAddress:
          $ref: ../../common/v1/Address.yaml#/components/schemas/Address
        contact:
          $ref: ../../common/v1/Contact.yaml#/components/schemas/Contact
        fulfillments:
          type: array
          description: Fulfillments for order
          items:
            $ref: ./Fulfillment.yaml#/components/schemas/Fulfillment
        refunds:
          type: array
          description: Refunds for order
          items:
            $ref: ../../payment/v1/Refund.yaml#/components/schemas/Refund
        links:
          type: array
          description: Links associated with order
          items:
            $ref: ../../common/v1/Link.yaml#/components/schemas/Link
        orderLineItems:
          type: array
          description: Line items in the order
          items:
            $ref: ./OrderLineItem.yaml#/components/schemas/OrderLineItem
        insuranceAmount:
          $ref: ../../common/v1/Money.yaml#/components/schemas/Money
        fees:
          type: array
          description: Fees in the order
          items:
            $ref: ../../common/v1/Fee.yaml#/components/schemas/Fee
        payments:
          type: array
          items:
            $ref: ../../common/v1/Link.yaml#/components/schemas/Link
